name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  REDIS_VERISON: 7.0.9-1

jobs:

  x86-jammy:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: ubuntu:jammy
      osversion: ubuntu22.04
      osnick: jammy
      build_deps: apt-get update && apt-get install -y wget curl make git lsb-release
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-focal:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: ubuntu:focal
      osversion: ubuntu20.04
      osnick: focal
      build_deps: apt-get update && apt-get install -y wget curl make git lsb-release
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-bionic:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: ubuntu:bionic
      osversion: ubuntu18.04
      osnick: bionic
      build_deps: apt-get update && apt-get install -y wget curl make git lsb-release
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-xenial:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: ubuntu:xenial
      osversion: ubuntu16.04
      osnick: xenial
      build_deps: apt-get update && apt-get install -y wget curl make git lsb-release
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-bullseye:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: debian:bullseye
      osversion: bullseye
      osnick: bullseye
      build_deps: apt-get update && apt-get install -y wget curl git redhat-lsb-core
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-rhel7:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: centos:7
      osversion: rhel7
      osnick: rhel7
      build_deps: |
        yum install -y epel-release
        yum install -y make wget git
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  x86-rhel8:
    uses: ./.github/workflows/REUSABLE.yml
    with:
      image_name: rockylinux:8
      osversion: rhel8
      osnick: rhel8
      build_deps: |
        yum install -y epel-release
        yum install -y make wget git redhat-lsb-core
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
