name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: install test deps
        run: pip install -r tests/requirements.txt

      - name: build debug
        run:
          cargo build

      - name: build release
        run:
          cargo build --release